//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncredibleInvoicer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int ItemID { get; set; }
        public string Item { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string HSNCode { get; set; }
    
        public virtual Customer Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual Unit Units { get; set; }
    }
}
